version: "3"

services:
  # app:
  #   container_name: csharp-app
  #   # image: mcr.microsoft.com/dotnet/samples:latest
  #   build:
  #     context: src/Flashcard.Api
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:80
  #   environment:
  #     - ASPENETCORE_ENVIRONMENT=Development
  db:
    image: mongo
    container_name: mongo-db
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    restart: unless-stopped
